# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-13 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('file_size', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='static/upload')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
    ]
