# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
