# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-05-14 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190513_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to='imgpath'),
        ),
    ]
