# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to='index/upload'),
        ),
    ]
